color: null
fieldLayouts:
  0f78c501-2370-469c-9f6e-f3101e987b4d:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-04-22T12:47:05+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 32594a6c-9c67-4fd8-a584-1ff68489e5e7
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-04-22T12:48:50+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: c94981df-856f-4761-874e-277e48585b5b # Rich Text
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3f766837-4e3d-4c3e-9cb6-3e8bdec8d1bd
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: c9214f13-d28e-48a3-ba10-7ceff7c6f420
        userCondition: null
handle: richTextBlock
hasTitleField: true
icon: subtitles
name: 'Rich Text Block'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
