altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  bca8fb46-c321-4955-9ae8-17960f9cce1d:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-04-22T11:28:57+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 044d2911-0fe1-4944-a325-db04ea079ccd
            userCondition: null
            warning: null
            width: 100
        name: Inhoud
        uid: a4ae254c-19c6-4cce-aee0-becb4a5a9dca
        userCondition: null
fs: localfs
handle: icons
name: Icons
sortOrder: 2
subpath: icons
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: localfs
transformSubpath: ''
