altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  c4bdb826-6884-44f7-9f28-2fea4c0cc166:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-04-22T12:20:55+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: cbdd2d0e-4289-468c-91c7-739dfc4c7e19
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 3e2d933c-7a39-4829-bbbc-6fc1423d954c
        userCondition: null
fs: localfs
handle: images
name: Images
sortOrder: 3
subpath: images
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: localfs
transformSubpath: ''
