altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  2987e6b9-bb37-4de7-854e-b40299f791bb:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-04-22T11:28:10+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 053e53b2-9d5b-499c-99e8-476393b4856e
            userCondition: null
            warning: null
            width: 100
        name: Inhoud
        uid: f8ca1cfb-bf50-4af7-9ee9-7aa1b571f591
        userCondition: null
fs: localfs
handle: photos
name: Photos
sortOrder: 1
subpath: photos
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: localfs
transformSubpath: ''
